### ISSUE TITLE
IPromise can notify during process

### ISSUE THREAD

**Issue by firehist** [nimaen/mighty-js#10]
On promise u can notify as u success and fail.
Its use full when u upload a file or when u perform a large job to know the current progress.

This old project implement Promise in typescript:https://github.com/pragmatrix/Promise.

Maybe we can externalize Promise implementation for typescript?

**Comment by nimaen** [comment]
Indeed, it would be a nice thing to add a progress register handler.
I'll push a draft of a promise implementation called *Pledge* and based on the JS Promise API.
