### ISSUE TITLE
Should we never got dist folder?

### ISSUE THREAD

**Issue by firehist** [nimaen/mighty-js#9]
I think that its a better way to never commit dist folder. This repo is for source but our CI will publish on separated repo for bower `bower-mighty-js` and specific npm publish part.

**Comment by nimaen** [comment]
:+1: I agree. 
Therefore, we won't waste our time merging compiled versions.

**Comment by firehist** [comment]
Can I close it ? 👯

**Comment by nimaen** [comment]
You can :wink:

**Comment by firehist** [comment]
Awesome
